### ISSUE TITLE
revisit the jest import error and our workaround

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#48]
Currently we are using an ugly workaround to avoid the jest / babel bug that causes jest to not transpile es modules imports.

The workaround is to re-add jest as a dev dependency after installing everything, see: https://github.com/CraveFood/farmblocks/blob/2496b87128fc0c0cfa01f60c5208da3e23911adc/.travis.yml#L25

But after updating yarn to 1.2.1 that workaround will no longer work. So we need a permanent fix.

Some (old?) references / hints:

- https://github.com/storybooks/storybook/issues/910
- https://github.com/storybooks/storybook/issues/880
- https://github.com/facebook/jest/issues/1468#issuecomment-276753756

**Comment by fczuardi** [comment]
ok, so here is the error:

```
 FAIL  ./Storyshots.test.js
  ● Test suite failed to run

    /Users/fabricio/mnmo/active/crave/farmblocks/node_modules/@crave/farmblocks-alert/src/index.story.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from "react";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at node_modules/@storybook/addon-storyshots/dist/require_context.js:39:24
          at Array.forEach (<anonymous>)
      at requireModules (node_modules/@storybook/addon-storyshots/dist/require_context.js:34:9)
      at node_modules/@storybook/addon-storyshots/dist/require_context.js:48:7
          at Array.forEach (<anonymous>)
```

After some investigation, the problem seem to be with the storybook config file, that currently use the following regex to find story.js files:

```
const req = require.context("../", true, /\.story\.js$/);
```

And this broad regex will include .story.js files that lives under node_modules, and packages/something/node_modules :(

I will submit a PR with a better regex that exclude node_modules subfolders...
